### PR TITLE
RALI added to MIVisionX

### PR DESCRIPTION
**Pull request by kiritigowda**

### CODE REVIEW

**Comment by kiritigowda** [comment]
@paveltc & @Reza-Najafi verify if this PR is good to be merged.

**Comment by Reza-Najafi** [comment]
Looks good

**Comment by kiritigowda** [comment]
@Reza-Najafi can you run the tests on the PR to make sure we did not break anything.

**Comment by Reza-Najafi** [comment]
> @Reza-Najafi can you run the tests on the PR to make sure we did not break anything.

I can test Rali related features, is this PR include same changes as the PR from my forked version to the develop branch?

**Comment by Reza-Najafi** [comment]
> @Reza-Najafi can you run the tests on the PR to make sure we did not break anything.

I cloned the PR built and installed the libraries and could run all RALI unit tests (which uses OpenVX) as well as rpp_vx extension tests. Demo app runs fine as well.

**Pull request merged**
