### PR TITLE
Documentation - Add Doxygen to Read the Docs site

### PR DESCRIPTION
**Pull request by samjwu**
directly integrates the Doxygen documentation via doxysphinx.

https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/doxygen/html/index.html

### CODE REVIEW

**Comment by kiritigowda** [comment]
@samjwu The Document is building fine, just need fix/enhance the following 

* OpenVX API is nested inside AMD OpenVX Library page, can it be on the same level as AMD OpenVX Library?
* The Document seems to not be generating all the functions. most api functions are here =-> https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/master/amd_openvx/openvx/include/VX/vx_api.h
* Here is the sample how this is generated in  OpenVX - https://registry.khronos.org/OpenVX/specs/1.3.1/html/OpenVX_Specification_1_3_1.html#group_vision_functions
* Let me know if you need any changes from TOT

**Comment by samjwu** [comment]
> * OpenVX API is nested inside AMD OpenVX Library page, can it be on the same level as AMD OpenVX Library?

Done: https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/amd_openvx/openvx/api.html

> * The Document seems to not be generating all the functions. most api functions are here =-> https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/master/amd_openvx/openvx/include/VX/vx_api.h

I've included the header files that seem to have Doxygen docstrings in the conf.py (https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/c7bac405e5fb81c69a35773675237aad1033e3d4/docs/conf.py) nested under whichever library is relevant. Is there a different particular order or format you'd prefer?

> * Here is the sample how this is generated in  OpenVX - https://registry.khronos.org/OpenVX/specs/1.3.1/html/OpenVX_Specification_1_3_1.html#group_vision_functions

Should [this page](https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/amd_openvx/openvx/api.html) list the functions in the same order as in the sample?

**Comment by samjwu** [comment]
Since the Doxygen output already uses the main README as the main doc page, I've placed it directly as the root of the doc site as well.

https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/doxygen/html/index.html#
https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/doxygen/html/modules.html
https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/doxygen/html/annotated.html
https://advanced-micro-devices-demo--1132.com.readthedocs.build/projects/MIVisionX/en/1132/doxygen/html/files.html

**Comment by kiritigowda** [comment]
@samjwu lets discuss this PR in our call tomorrow.

**Comment by kiritigowda** [comment]
@samjwu can I  merge this as first step and we can add the enhancements?

**Pull request merged**
