### PR TITLE
License Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
* Fix for license dates
* Fix for missing license

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 PR builds without any errors.

**Comment by LakshmiKumar23** [comment]
@kiritigowda The CI build fails. Can you check it out?

**Comment by kiritigowda** [comment]
> @kiritigowda The CI build fails. Can you check it out?

@LakshmiKumar23 the CI has problems with Travis. Nothing to do with us.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Ok I am running the build now. Will approve once it finishes

**Pull request merged**
