### PR TITLE
Tests - Conformance Test Script

### PR DESCRIPTION
**Pull request by kiritigowda**
* Run CTS on Linux
* Backend Support - ALL, HOST, OCL, & HIP
* Save CTS LOGs & System Info

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 could you run this script?

**Review by asalmanp — APPROVED** [review]

**Comment by LakshmiKumar23** [comment]
@kiritigowda I ran this script and used the --directory option to current folder 
```
 python3.8 runConformanceTests.py --directory . --backend_type OCL
```

Not sure if that's the reason, but seems like it's looking for the .so files in a particular folder
```
/usr/bin/ld: cannot find -l./mivisionx-conformance/build-opencl/lib/libopenvx.so
/usr/bin/ld: cannot find -l./mivisionx-conformance/build-opencl/lib/libvxu.so
collect2: error: ld returned 1 exit status
make[2]: *** [test_conformance/CMakeFiles/vx_test_conformance.dir/build.make:1180: bin/vx_test_conformance] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: test_conformance/CMakeFiles/vx_test_conformance.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
sh: 1: ./bin/vx_test_conformance: not found
sh: 1: ./bin/vx_test_conformance: not found
```

**Comment by LakshmiKumar23** [comment]
> > @kiritigowda I ran this script and used the --directory option to current folder
> > ```
> >  python3.8 runConformanceTests.py --directory . --backend_type OCL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure if that's the reason, but seems like it's looking for the .so files in a particular folder
> > ```
> > /usr/bin/ld: cannot find -l./mivisionx-conformance/build-opencl/lib/libopenvx.so
> > /usr/bin/ld: cannot find -l./mivisionx-conformance/build-opencl/lib/libvxu.so
> > collect2: error: ld returned 1 exit status
> > make[2]: *** [test_conformance/CMakeFiles/vx_test_conformance.dir/build.make:1180: bin/vx_test_conformance] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:231: test_conformance/CMakeFiles/vx_test_conformance.dir/all] Error 2
> > make: *** [Makefile:130: all] Error 2
> > sh: 1: ./bin/vx_test_conformance: not found
> > sh: 1: ./bin/vx_test_conformance: not found
> > ```
> 
> @LakshmiKumar23 can you try without the --directory option for now? I will look into this issue. Make sure this generates logs for the backend specified?

@kiritigowda Works with default directory

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you verify that all the tests are passing in the logs saved?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 all issues have been resolved

**Pull request merged**
