### PR TITLE
WIP: RunVX - OpenSSL Updates

### PR DESCRIPTION
**Pull request by kiritigowda**
Remove deprecated functions
Use EVP Message Digests

### CODE REVIEW

**Comment by kiritigowda** [comment]
@paveltc please verify functionality.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you test this?

**Comment by paveltc** [comment]
@kiritigowda I'm seeing the following error when running checksum comparisons: 
runVX - OpenSSL ERROR: EVP_DigestFinal_ex() failed

**Comment by paveltc** [comment]
@kiritigowda Did you take a look at the issue that I mentioned?
runVX - OpenSSL ERROR: EVP_DigestFinal_ex() failed

**Comment by kiritigowda** [comment]
@paveltc I reopen this pr with the fixes.

**Pull request closed without merging**
