### PR TITLE
Rr/mcw rali

### PR DESCRIPTION
**Pull request by rrawther**
This is the latest changes for RALI form MCW

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@rrawther Can you check this. The CI fails to build. I can test it once it builds

**Comment by rrawther** [comment]
Also pushed changes for cifar10 data loader  for RALI

**Comment by rrawther** [comment]
@kiritigowda Can you merge this. The build was failing because RPP was not merged

**Comment by kiritigowda** [comment]
@rrawther can you look at LGTM alerts

**Comment by kiritigowda** [comment]
@rrawther passing CI with updates to dependencies and RPP V0.3, this is read to be merged.
 Is this branch ready?

**Pull request merged**
