### PR TITLE
rocAL - python package improvisation wrt installation

### PR DESCRIPTION
**Pull request by fiona-gladwin**
Modified run.sh script to install and remove the respective python packages in the corresponding environments.

### CODE REVIEW

**Review by rrawther — COMMENTED** [review]
@LakshmiKumar23: Can you please check if this works on stand alone environment as well as in ROCm pytoch docker.

**Comment by LakshmiKumar23** [comment]
@rrawther @fiona-gladwin Will running the run.sh and test.py following this be enough for testing? What other tests are you running on this?

**Comment by fiona-gladwin** [comment]
Regarding testing
- Please test the rocAL python package for the following cases
    - without a conda environment
    - inside a conda environment
    - inside a rocm pytorch docker

You can add print statements in [pipeline.py](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/master/rocAL/rocAL_pybind/amd/rali/pipeline.py) file and build the python package(using the command ./run.sh) for the above cases. Run the tests.py file to ensure that the changes in the python files have been reflected only in that particular environment.

**Review by rrawther — APPROVED** [review]
@LakshmiKumar23 : please confirm this works in both environments

**Comment by rrawther** [comment]
Lakshmi tested it and it is good to merge

**Comment by kiritigowda** [comment]
CI Results Pending for merge - http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2FShort-GPUOpen%2FMIVisionX/detail/PR-622/2/pipeline

**Review by LakshmiKumar23 — APPROVED** [review]

**Pull request merged**
