### PR TITLE
VX_OpenCV - OpenCV V4.X Support

### PR DESCRIPTION
**Pull request by kiritigowda**
* Version 4.X.X support 
  + VX OpenCV EXT
  + RunVX

@paveltc need to test with some visual samples

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 tested with below version
```
brew info OpenCV
opencv: stable 4.5.4 (bottled)
Open source computer vision library
https://opencv.org/
/usr/local/Cellar/opencv/4.5.4_3 (852 files, 236.7MB) *
  Poured from bottle on 2022-01-31 at 17:01:37
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opencv.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: ceres-solver ✔, eigen ✔, ffmpeg ✔, glog ✔, harfbuzz ✔, jpeg ✔, libpng ✔, libtiff ✔, numpy ✔, openblas ✔, openexr ✔, protobuf ✔, python@3.9 ✔, tbb ✔, vtk ✔, webp ✔
==> Analytics
install: 19,156 (30 days), 52,429 (90 days), 184,756 (365 days)
install-on-request: 18,310 (30 days), 50,120 (90 days), 177,069 (365 days)
build-error: 198 (30 days)
```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 @paveltc use OpenCV `3.4.X` & `4.5.X` to test.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Looks okay to me. Shouldn't effect any of the docker files.

**Comment by kiritigowda** [comment]
> @kiritigowda Looks okay to me. Shouldn't effect any of the docker files. We aren't planning on changing the setup script to bring OpenCV 4.x right? This is only if the user already has it?

Yes, @LakshmiKumar23 this will not change any current functionality, and all tests should pass as usual. This adds support if the host machine has 4.X OpenCV.

**Pull request merged**
