### PR TITLE
Model Compiler README updates

### PR DESCRIPTION
**Pull request by LakshmiKumar23**

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely can you try these instructions on `CAFFE`/`ONNX`/`NNEF` models.

**Comment by kiritigowda** [comment]
@hansely any updates?

**Comment by hansely** [comment]
onnx->nnir : O
nnef->nnir: O
caffe->nnir: X

Traceback (most recent call last):
  File "caffe_to_nnir.py", line 913, in <module>
    main()
  File "caffe_to_nnir.py", line 910, in main
    caffe2ir(net_parameter, input_dims, outputFolder, verbose, node_type_append)
  File "caffe_to_nnir.py", line 866, in caffe2ir
    graph = caffe_graph_to_ir_graph(net_parameter, input_dims, verbose)
  File "caffe_to_nnir.py", line 859, in caffe_graph_to_ir_graph
    inputOutputMap, output_name = extractCaffeNodeInfo(net_parameter, graph, inputMap, verbose)
  File "caffe_to_nnir.py", line 804, in extractCaffeNodeInfo
    dimList = calculateTensorDims(layer_param, input_info_map, attribute_map)
  File "caffe_to_nnir.py", line 364, in calculateTensorDims
    n,c,h,w = input_map[inputs[0]]
TypeError: 'odict_keys' object does not support indexing

nnir->openvx : X

  File "nnir_to_openvx.py", line 1642
    elif input_data_type == "F016":
                                  ^

Probably the indexing is different in python3.

**Comment by LakshmiKumar23** [comment]
@hansely Did you use verbose 1 in the caffe_to_nnir script? Is that when you saw the error?
@paveltc I don't remember you mentioning this. Did you see this error too?

**Comment by kiritigowda** [comment]
@hansely any updates on this?

**Comment by hansely** [comment]
@kiritigowda 
I already talked to Lakshmi about this. We are waiting for @paveltc for his comments. 
Once he confirms it, this PR may be merged.

**Comment by paveltc** [comment]
@LakshmiKumar23 I did not see that error. Is it still reproducible?

**Comment by LakshmiKumar23** [comment]
@paveltc I cannot reproduce it either. Only @hansely saw it.

**Pull request merged**
