### PR TITLE
Model Compiler - ONNX update

### PR DESCRIPTION
**Pull request by hansely**
-updated the onnx_to_nnir python script to handle different tensor data values which fixes the empty raw data files

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely can you sync with master

**Comment by kiritigowda** [comment]
@hansely can you look at the codacy issues?

**Comment by hansely** [comment]
@kiritigowda codacy fixed and synced with develop(not master)

**Comment by paveltc** [comment]
@kiritigowda @hansely I tested this and it seems to fix the problems with ONNX.

**Pull request merged**
