### PR TITLE
MIVisionX Backend - Default GPU backend: HIP

### PR DESCRIPTION
**Pull request by asalmanp**
This PR makes the HIP the default GPU backend for the MIVisionX. We need to test all the samples/tests/apps.

- To run the prerequisites for the default setting (i.e., HIP backend) just run **MIVisionX-setup.py** and use **cmake ..** to build the mivisionx with the HIP backend.

- To run the prerequisites for the OCL backend just run **MIVisionX-setup.py --reinstall yes --backend OCL** and use **cmake -DBACKEND=OCL ..** to build the mivisionx with the OCL backend.

### CODE REVIEW

**Comment by paveltc** [comment]
@asalmanp @kiritigowda @LakshmiKumar23 I have run unit tests on OpenVX, NN extension and rocAL and they all seem fine.

**Comment by kiritigowda** [comment]
@asalmanp with this change to develop, let's release the tag 2.0.1 from master and update the version to 2.1.0 as its HIP backend vs OpenCL backend moving forward. Also, there is a merge conflict.

**Comment by LakshmiKumar23** [comment]
@asalmanp @kiritigowda tested some of the apps

-  optical flow, classifier and analyzer - works.
- validation needs updating wrt rocAL, can only test after that
 (others are being tested by @hansely )

**Review by LakshmiKumar23 — APPROVED** [review]

**Comment by hansely** [comment]
@kiritigowda @asalmanp @LakshmiKumar23 
-dg test - works
-inference server app - works
-image augmentation - works
-bubble pop - needs re-testing after the recent update

**Pull request merged**
