### PR TITLE
Appending node type to local tensor names for calibration

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
New command line argument for caffe_to_nnir, onnx_to_nnir, nnef_to_nnir , nnir_update to take 'node_type_append'.

Appends type of the node to local tensor names, when needed for calibration

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this ready to be merged?

**Comment by LakshmiKumar23** [comment]
@kiritigowda yes

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this ok to merge now?

**Comment by LakshmiKumar23** [comment]
@kiritigowda I think this needs to be merged with the master. Let me do that and see if it gives any merge conflicts.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Ready to be merged now

**Pull request merged**
