### PR TITLE
Boost Updates - MIOpen Install Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
* NN setup Fix
* Docker Updates

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 & @paveltc - build the full stack with this change - http://math-ci.rocm.amd.com/job/compute-rocm-dkms-no-npi-hipclang/job/Short-GPUOpen/job/MIVisionX/job/PR-517/1/artifact/kUaaKeLq0/mivisionx/build/release-opencl/package/mivisionx-2.0.0.40200-local.el7.x86_64.rpm/*view*

**Comment by LakshmiKumar23** [comment]
@kiritigowda I still see the same issue even with the PR. 

-- WARNING:OpenCL/MIOpen/MIOpenGEMM Not Found -- amd_nn module excluded

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 & @paveltc - build the full stack with this change - http://math-ci.rocm.amd.com/job/compute-rocm-dkms-no-npi-hipclang/job/Short-GPUOpen/job/MIVisionX/job/PR-517/1/artifact/kUaaKeLq0/mivisionx/build/release-opencl/package/mivisionx-2.0.0.40200-local.el7.x86_64.rpm/*view*

@kiritigowda Cannot acces this link. But testing out the PR now.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Builds amn_nn. Can be merged

**Review by LakshmiKumar23 — APPROVED** [review]

**Comment by paveltc** [comment]
@kiritigowda It successfully builds and installs with this PR.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 @paveltc i got the miopen team to fix 2.11, will update the pr. https://github.com/ROCmSoftwarePlatform/MIOpen/issues/965

**Pull request merged**
