### PR TITLE
fix for issue #265

### PR DESCRIPTION
**Pull request by rrawther**
Fixes the hang for issue #265

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely can you check if this fix works?

**Comment by hansely** [comment]
It still hangs sometimes. It's the timing issue. 
If the wait() function is called before notify_one() is called, then it works. However, if notify_one() is called before wait(), then it hangs.

**Comment by hansely** [comment]
So basically, if the thread working on releaseGraph() function starts working even before the createGraph() is finished, then it hangs.

**Comment by hansely** [comment]
Nevermind. I was running a different branch. Please disregard my previous comments. 
This fixes the bug.

**Pull request merged**
