### PR TITLE
rocAL - TOT fix

### PR DESCRIPTION
**Pull request by swetha097**
Add back the CopyToTensorNCHW/NHWC to fix the TOT

### CODE REVIEW

**Review by rrawther — APPROVED** [review]
@LakshmiKumar23: please verify it works with existing trainings

**Comment by kiritigowda** [comment]
@LakshmiKumar23 let me know when this is ready to merge?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 let me know when this is ready to merge?

@kiritigowda We are focusing on closing PR724 first, so this might not be merged until later. This is trying to fix the old API

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can we close this?

**Comment by LakshmiKumar23** [comment]
@kiritigowda We can close it for now

**Pull request closed without merging**
