### PR TITLE
 MIVisionX Setup Script Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
* sudo requirement removed
* fixed bugs

### CODE REVIEW

**Comment by jlgreathouse** [comment]
LGTM for the the issues it's aiming to fix, thanks!

What are your thoughts of putting `#! /usr/bin/env python` on the first line and `chmod +x` the script so that it could be run directly (`./MIVisionX-setup.py`) instead of having to call `python MIVisionX-setup.py`?

**Comment by kiritigowda** [comment]
> LGTM for the the issues it's aiming to fix, thanks!
> 
> What are your thoughts of putting `#! /usr/bin/env python` on the first line and `chmod +x` the script so that it could be run directly (`./MIVisionX-setup.py`) instead of having to call `python MIVisionX-setup.py`?

@jlgreathouse Thanks for reporting these issues. I will merge this to the master. Please do report any problems or bugs you encounter. 

Any particular reason for having `./MIVisionX-setup.py` instead of the `python MIVisionX-setup.py`?

**Comment by jlgreathouse** [comment]
@kiritigowda on Linux anyway, it's usually common practice for scripts to be executable directly. It's the whole reason for [the hashbang mechanism](https://en.wikipedia.org/wiki/Shebang_(Unix)) is to treat scripts as executables so you don't need to personally know what interpreter is being used.

**Comment by kiritigowda** [comment]
@jlgreathouse thanks for the information, I will make those changes in my next commit.

**Pull request merged**
