### PR TITLE
vxCreateUniformImage API - adding support for VX_DF_IMAGE_U8

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
@rrawther we spoke about this during image containment relationship, and found it to be missing. Just adding that in this PR

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this ready to be merged?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Yes, it is

**Review by kiritigowda — APPROVED** [review]

**Comment by kiritigowda** [comment]
@rrawther approval pending for merge

**Review by rrawther — APPROVED** [review]
make sure the unit tests pass with this

**Pull request merged**
