### PR TITLE
added support to decode up to 16 streams

### PR DESCRIPTION
**Pull request by rrawther**
Added option in the app to decode batch_size 8 and 16 simultaneously

### CODE REVIEW

**Comment by kiritigowda** [comment]
@rrawther having problem building this PR

```
MIVisionX/samples/inference/mv_objdetect/build# cmake ../
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenCL.cmake:132 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/MIVisionX/MIVisionX/samples/inference/mv_objdetect/build/CMakeFiles/CMakeOutput.log".
See also "/root/MIVisionX/MIVisionX/samples/inference/mv_objdetect/build/CMakeFiles/CMakeError.log".
```

**Comment by kiritigowda** [comment]
#135 is linked to this PR

**Comment by rrawther** [comment]
@kiritigowda : This sample would not build by just doing CMake. Please follow the steps in README to build it using mv_compile utility. Please let me know if there is issues

**Comment by kiritigowda** [comment]
@rrawther I am getting the following errors

```
root@simon:~# mv_compile --model ../yoloV2Tiny20.caffemodel --install_folder mvdeploy --input_dims 1,3,416,416
compiling model for backend OpenVX_Rocm_OpenCL
Env MIVISIONX_MODEL_COMPILER_PATH is not specified, using default /opt/rocm/mivisionx/model_compiler
Error in importing model to MIVisionX
root@simon:~# MIVISIONX_MODEL_COMPILER_PATH=/opt/rocm/mivisionx/model_compiler mv_compile --model ../yoloV2Tiny20.caffemodel --install_folder mvdeploy --input_dims 1,3,416,416
compiling model for backend OpenVX_Rocm_OpenCL
Error in importing model to MIVisionX

```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you try this PR on the docker - port-forwarding-enabled

**Comment by rrawther** [comment]
@kiritigowda : mv_compile utility gets installed with MIVisionX in /opt/rocm/mivisionx/bin. If you have that in your path, it shouldn't cause any issues. I guess you are trying to run with an old version of model_compiler

**Comment by LakshmiKumar23** [comment]
I ran this on the docker ssh-port-forward-enable:
`/opt/rocm/mivisionx/bin/mv_compile --model yoloV2Tiny20.caffemodel --install_folder mvdeploy --input_dims 1,3,416,416
compiling model for backend OpenVX_Rocm_OpenCL
Env MIVISIONX_MODEL_COMPILER_PATH is not specified, using default /opt/rocm/mivisionx/model_compiler
INFO: executing: % python /opt/rocm/mivisionx/model_compiler/python/caffe_to_nnir.py yoloV2Tiny20.caffemodel nnir-output --input-dims 1,3,416,416
OK: loading caffemodel from yoloV2Tiny20.caffemodel ...
OK: caffemodel read successful
converting to AMD NNIR format in nnir-output folder ...
OK: creating IR description in nnir-output/graph.nnir ...
OK: creating IR binaries in nnir-output/binary ...
OK: graph successfully formed.
INFO: executing: % python /opt/rocm/mivisionx/model_compiler/python/nnir_to_clib.py nnir-output mvdeploy>>nnir_to_clib.log
INFO: nnir_to_clib generated completed (0)
INFO: executing: % cmake ../ >>../cmake.log
INFO: executing: % make >>../make.log
OK: MIVisionX model compilation Successful`

**Comment by rrawther** [comment]
@LakshmiKumar23 Can you please test the entire sample following the steps. Make sure you test with batch_size 8 and batch_size 16 as well

**Comment by LakshmiKumar23** [comment]
@rrawther I get the following error:

```
./bin/mvtestdeploy ./data/images/img_04.JPG output.bin --install_folder . --t 100
Success::loading deployment library ./lib/libmv_deploy.so
Config_input::<1 3 416 416>:data
Config_output::<1 125 12 12>:conv_conv9
OK: loaded 32 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx906+sram-ecc) [OpenCL 2.0 ] [SvmCaps 0 0]
OK::mvCreateInferenceSession
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /root/mivisionx-deps/opencv-3.4.0/modules/imgproc/src/resize.cpp, line 4044
terminate called after throwing an instance of 'cv::Exception'
  what():  /root/mivisionx-deps/opencv-3.4.0/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Aborted (core dumped)
```


Also, there is no data folder under mvdeploy after the first step.

**Comment by kiritigowda** [comment]
@rrawther & @LakshmiKumar23 I am seeing the same problem

```
root@simon:~# mv_compile --model yoloV2Tiny20.caffemodel --install_folder mvdeploy --input_dims 1,3,416,416
compiling model for backend OpenVX_Rocm_OpenCL
Env MIVISIONX_MODEL_COMPILER_PATH is not specified, using default /opt/rocm/mivisionx/model_compiler
INFO: executing: % python /opt/rocm/mivisionx/model_compiler/python/caffe_to_nnir.py yoloV2Tiny20.caffemodel nnir-output --input-dims 1,3,416,416
OK: loading caffemodel from yoloV2Tiny20.caffemodel ...
OK: caffemodel read successful
converting to AMD NNIR format in nnir-output folder ...
OK: creating IR description in nnir-output/graph.nnir ...
OK: creating IR binaries in nnir-output/binary ...
OK: graph successfully formed.
INFO: executing: % python /opt/rocm/mivisionx/model_compiler/python/nnir_to_clib.py nnir-output mvdeploy>>nnir_to_clib.log
INFO: nnir_to_clib generated completed (0)
INFO: executing: % cmake ../ >>../cmake.log
INFO: executing: % make >>../make.log
OK: MIVisionX model compilation Successful
root@simon:~# cd mvdeploy
root@simon:~/mvdeploy# ./bin/mvtestdeploy ./data/images/img_04.JPG output.bin --install_folder . --t 100
Success::loading deployment library ./lib/libmv_deploy.so
Config_input::<1 3 416 416>:data
Config_output::<1 125 12 12>:conv9
OK: loaded 32 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx906+sram-ecc) [OpenCL 2.0 ] [SvmCaps 0 0]
OK::mvCreateInferenceSession
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /root/mivisionx-deps/opencv-3.4.0/modules/imgproc/src/resize.cpp, line 4044
terminate called after throwing an instance of 'cv::Exception'
  what():  /root/mivisionx-deps/opencv-3.4.0/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Aborted (core dumped)
```

**Comment by rrawther** [comment]
@LakshmiKumar23  and @kiritigowda : the reason you are both getting the error is because of the incorrect path for input image. I have updated the README.txt for the correct path. Also updated some input files. Please try again

**Comment by kiritigowda** [comment]
@rrawther PR updates successfully builds.
```
root@simon:~/mvdeploy# ./bin/mvtestdeploy ../MIVisionX/MIVisionX/samples/inference/mv_objdetect/data/images/img_04.JPG output.bin --install_folser . --t 100
Success::loading deployment library ./lib/libmv_deploy.so
Config_input::<1 3 416 416>:data
Config_output::<1 125 12 12>:conv9
OK: loaded 32 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx906+sram-ecc) [OpenCL 2.0 ] [SvmCaps 0 0]
OK::mvCreateInferenceSession
OK: mvProcessInference() took 23.648 msec (average over 100 iterations)
OK: mvRunInference() took 23.648 msec (average over 100 iterations)
OK: OpenCL buffer usage: 87771380, 46/46
OK: Inference Deploy Successful
```
@LakshmiKumar23 please verify.

**Comment by LakshmiKumar23** [comment]
> ../MIVisionX/MIVisionX/samples/inference/mv_objdetect/data/images/img_04.JPG

@kiritigowda Did you give this whole path yourseld? Becasu this isn't on the READ. If I run the README as is it still fails

**Comment by LakshmiKumar23** [comment]
@rrawther If I give the path like Kiriti, it says successfull. But the next step `cp ../mvobjdetect.cpp ../visualize.cpp ../visualize.h ../CMakeLists.txt .` the paths are wrong again

**Pull request merged**
