### PR TITLE
VX RPP & RALI - FIX

### PR DESCRIPTION
**Pull request by kiritigowda**
* CMakeList Fix
* Header links fix
* Export headers fix
* Hardcoded path removal

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you try to build this branch and let me know

**Comment by kiritigowda** [comment]
@paveltc can you run RALI and AMD_VX_RPP tests on this branch

**Comment by kiritigowda** [comment]
> @LakshmiKumar23 can you try to build this branch and let me know

@LakshmiKumar23 can you verify this branch?

**Comment by kiritigowda** [comment]
@rrawther can you verify this PR.

**Comment by LakshmiKumar23** [comment]
@kiritigowda builds successfully

**Comment by kiritigowda** [comment]
@rrawther this branch has been tested by @paveltc. No deviations from the master in testing results.

**Pull request merged**
