### PR TITLE
Validation app update - new rocAL API

### PR DESCRIPTION
**Pull request by LakshmiKumar23**

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this ready to be merged into develop?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 is this ready to be merged into develop?
@kiritigowda Hansel and I are finalizing this PR now. Can maybe merge by EOD. We will keep you posted

**Comment by LakshmiKumar23** [comment]
Fixes #644

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this ready to be merged?

**Comment by LakshmiKumar23** [comment]
@kiritigowda yes it is

**Review by kiritigowda — APPROVED** [review]

**Pull request merged**
