### PR TITLE
Docker - Updates to half & Pytorch install

### PR DESCRIPTION
**Pull request by kiritigowda**
Docker 

* Half install updates
* PyTorch docker updates

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@kiritigowda Still seeing this error with the pytorch docker 
```
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get -y install wget libbz2-dev libssl-dev python-dev python3-dev libgflags-dev libgoogle-glog-dev liblmdb-dev nasm yasm libjsoncpp-dev clang &&         git clone -b 2.0.6.1 https://github.com/rrawther/libjpeg-turbo.git && cd libjpeg-turbo && mkdir build && cd build &&         cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE -DENABLE_STATIC=FALSE -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/libjpeg-turbo-2.0.3         -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib ../ && make -j4 && sudo make install && cd ../../ &&         wget https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2 && tar xjvf boost_1_72_0.tar.bz2 &&         cd boost_1_72_0 && ./bootstrap.sh --prefix=/usr/local --with-python=python3 &&         ./b2 stage -j16 threading=multi link=shared cxxflags="-std=c++11" &&         sudo ./b2 install threading=multi link=shared --with-system --with-filesystem &&         ./b2 stage -j16 threading=multi link=static cxxflags="-std=c++11 -fpic" cflags="-fpic" &&         sudo ./b2 install threading=multi link=static --with-system --with-filesystem && cd ../ &&         git clone -b 0.93  https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp.git && cd rpp && mkdir build && cd build &&         cmake -DBACKEND=HIP ../ && make -j4 && sudo make install && cd ../../ &&         git clone -b v3.12.4 https://github.com/protocolbuffers/protobuf.git && cd protobuf && git submodule update --init --recursive &&         ./autogen.sh && ./configure && make -j8 && make check -j8 && sudo make install && sudo ldconfig && cd' returned a non-zero code: 1
```

**Comment by kiritigowda** [comment]
> 

`export CPLUS_INCLUDE_PATH=/usr/include/python3.8` -- Fix to accommodate multiple versions of python

**Comment by kiritigowda** [comment]
@LakshmiKumar23 - built on your system -- verify the docker

```
sudo docker build -f docker/pytorch/mivisionx-with-pytorch.dockerfile -t u20-pytorch .
[sudo] password for kiriti: 
Sending build context to Docker daemon  355.3MB
Step 1/12 : FROM rocm/pytorch:latest
 ---> b9fe7303d129
Step 2/12 : ENV MIVISIONX_DEPS_ROOT=/opt/mivisionx-deps
 ---> Using cache
 ---> 892632548ad8
Step 3/12 : WORKDIR $MIVISIONX_DEPS_ROOT
 ---> Using cache
 ---> 42c23e5b9729
Step 4/12 : RUN apt-get update -y
 ---> Using cache
 ---> 7f3802c73ab4
Step 5/12 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install gcc g++ cmake pkg-config git
 ---> Using cache
 ---> fdf095133dc1
Step 6/12 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install initramfs-tools libnuma-dev wget sudo keyboard-configuration
 ---> Using cache
 ---> 06f8693f0927
Step 7/12 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev python-dev python-numpy         libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev unzip &&         mkdir OpenCV && cd OpenCV && wget https://github.com/opencv/opencv/archive/4.5.5.zip && unzip 4.5.5.zip &&         mkdir build && cd build && cmake -DWITH_OPENCL=OFF ../opencv-4.5.5 && make -j8 && sudo make install && sudo ldconfig && cd
 ---> Using cache
 ---> fabe3f208822
Step 8/12 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install autoconf automake build-essential cmake git-core libass-dev libfreetype6-dev libsdl2-dev libtool libva-dev         libvdpau-dev libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev pkg-config texinfo wget zlib1g-dev         nasm yasm libx264-dev libx265-dev libnuma-dev libfdk-aac-dev &&         wget https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n4.4.2.zip && unzip n4.4.2.zip && cd FFmpeg-n4.4.2/ && sudo ldconfig &&         export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig/" &&         ./configure --enable-shared --disable-static --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libass --enable-gpl --enable-nonfree &&         make -j8 && sudo make install && cd
 ---> Using cache
 ---> eaef063f1054
Step 9/12 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install miopen-hip migraphx &&         mkdir neuralNet && cd neuralNet && wget https://sourceforge.net/projects/half/files/half/1.12.0/half-1.12.0.zip &&         unzip half-1.12.0.zip -d half-files && sudo mkdir -p /usr/local/include/half && sudo cp half-files/include/half.hpp /usr/local/include/half && cd
 ---> Using cache
 ---> 0f53cb29ddd5
Step 10/12 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y install wget libbz2-dev libssl-dev python3-dev libgflags-dev libgoogle-glog-dev liblmdb-dev nasm yasm libjsoncpp-dev clang &&         git clone -b 2.0.6.1 https://github.com/rrawther/libjpeg-turbo.git && cd libjpeg-turbo && mkdir build && cd build &&         cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE -DENABLE_STATIC=FALSE -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/libjpeg-turbo-2.0.3         -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib ../ && make -j4 && sudo make install && cd ../../ &&         wget https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2 && tar xjvf boost_1_72_0.tar.bz2 &&         export CPLUS_INCLUDE_PATH=/usr/include/python3.8 && cd boost_1_72_0 && ./bootstrap.sh --prefix=/usr/local --with-python=python3 &&         ./b2 stage -j16 threading=multi link=shared cxxflags="-std=c++11" &&         sudo ./b2 install threading=multi link=shared --with-system --with-filesystem &&         ./b2 stage -j16 threading=multi link=static cxxflags="-std=c++11 -fpic" cflags="-fpic" &&         sudo ./b2 install threading=multi link=static --with-system --with-filesystem && cd ../ &&         git clone -b 0.93  https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp.git && cd rpp && mkdir build && cd build &&         cmake -DBACKEND=HIP ../ && make -j4 && sudo make install && cd ../../ &&         git clone -b v3.12.4 https://github.com/protocolbuffers/protobuf.git && cd protobuf && git submodule update --init --recursive &&         ./autogen.sh && ./configure && make -j8 && make check -j8 && sudo make install && sudo ldconfig && cd
 ---> Using cache
 ---> aa1d99ba0e19
Step 11/12 : WORKDIR /workspace
 ---> Using cache
 ---> 14c3fe2040e3
Step 12/12 : RUN git clone https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX.git
 ---> Using cache
 ---> 24f8d129f977
Successfully built 24f8d129f977
Successfully tagged u20-pytorch:latest

```

**Review by LakshmiKumar23 — APPROVED** [review]
@kiritigowda Docker builds. Can be merged. 
Fixes issue #899

**Pull request merged**
