### PR TITLE
Neural Network Extension, HIP GPU backend - add support for gather layer

### PR DESCRIPTION
**Pull request by asalmanp**

### CODE REVIEW

**Review by rrawther — APPROVED** [review]
@paveltc : make sure the neural_inference tests pass with this PR

**Comment by asalmanp** [comment]
> @paveltc : make sure the neural_inference tests pass with this PR

@paveltc please note that you would need to run neural_inference tests with **OpenCL backend** only for this PR (i.e., as HIP backend doesn't have full support for all NN layers.)

**For HIP backend**, You can try to run the unit test for gather layer (i.e., (https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX-tests/tree/master/archive/layers-gdftests/gather). Both gdfs in this link should run and pass with HIP backend.

**Comment by kiritigowda** [comment]
Merge pending CI Completion - http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2FShort-GPUOpen%2FMIVisionX/detail/PR-575/1/pipeline

**Comment by paveltc** [comment]
All neural inference tests fail with this PR with the OpenCL backend. 
anntest gives the following error when running for all networks (Caffe and ONNX):
Preprocessing add: 0 0 0
Preprocessing multiply: 1 1 1
OK: initialized tensor 'data' from ../tensors-224x224/tensor-1-224x224.fp
OK: loaded 1 kernels from libvx_nn.so
createNode: failed to retrieve kernel enum 4096
ERROR: failed with status = (-7) at /home/svcbuild/mivisionx-pr575/MIVisionX-tests/vgg16-caffe-b1-ovx/annmodule.cpp#354
ERROR: annAddToGraph() failed (-7)

I have not run the test for the HIP backend gather layer yet as the OpenCL backend should probably be fixed first.

I have tested with TOT and all inference tests pass so the problem is in this PR.

**Comment by asalmanp** [comment]
> @asalmanp and @rrawther
> All neural inference tests **fail** with this PR with the OpenCL backend.
> 
> anntest gives the following error when running for all networks (Caffe and ONNX):
> _Preprocessing add: 0 0 0 Preprocessing multiply: 1 1 1 OK: initialized tensor 'data' from ../tensors-224x224/tensor-1-224x224.fp OK: loaded 1 kernels from libvx_nn.so createNode: failed to retrieve kernel enum 4096 ERROR: failed with status = (-7) at /home/svcbuild/mivisionx-pr575/MIVisionX-tests/vgg16-caffe-b1-ovx/annmodule.cpp#354 ERROR: annAddToGraph() failed (-7)_
> 
> I have not run the test for the HIP backend gather layer yet as the OpenCL backend should probably be fixed first.
> 
> **I have tested with TOT and all inference tests pass so the problem is in this PR.**

@paveltc I submitted a fix for the issue that you reported, please test again.

**Comment by paveltc** [comment]
@asalmanp Currently running the tests. Basic unit test has passed.

**Comment by paveltc** [comment]
@asalmanp 
All inference tests are now passing with OpenCL.
Gather layer tests with HIP:
gather_1.gdf: passes and the output matches the golden output
gather_2.gdf:
ERROR: vxGetKernelByName(context,"com.amd.nn_extension.gather_layer") failed (-7:VX_ERROR_NO_RESOURCES)

I checked the GDFs and am not sure why the error is coming up with the second GDF.

**Comment by paveltc** [comment]
Problem was with gather_2.gdf, it was missing import vx_nn at the top.
Now gather_2.gdf passes and matches the expected output.
All tests for this PR pass. Should be fine to merge.

**Pull request merged**
