### PR TITLE
Lk/docker update

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
TurboJPEG version update

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you also update the setup file?

**Review by rrawther — APPROVED** [review]
please merge it asap as it is breaking the training

**Comment by kiritigowda** [comment]
@LakshmiKumar23 also needs sync with TOT develop.

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 also needs sync with TOT develop.

@kiritigowda I just synced it

**Pull request merged**
