### PR TITLE
Crop and resize layer

### PR DESCRIPTION
**Pull request by hansely**
Crop and resize layer added.

### CODE REVIEW

**Comment by kiritigowda** [comment]
build failure on this branch

````
[ 43%] Building CXX object amd_openvx_extensions/amd_nn/CMakeFiles/vx_nn.dir/src/crop_and_resize_layer.cpp.o
/MIVisionX/amd_openvx_extensions/amd_nn/src/crop_and_resize_layer.cpp: In function 'vx_status publishCropAndResizeLayer(vx_context)':
/MIVisionX/amd_openvx_extensions/amd_nn/src/crop_and_resize_layer.cpp:240:95: error: 'VX_KERNEL_CROP_AND_RESIZE_LAYER_AMD' was not declared in this scope
     vx_kernel kernel = vxAddUserKernel(context, "com.amd.nn_extension.crop_and_resize_layer", VX_KERNEL_CROP_AND_RESIZE_LAYER_AMD, host_kernel, 8, validateCropAndResizeLayer, NULL, NULL);
                                                                                               ^
/MIVisionX/amd_openvx_extensions/amd_nn/src/crop_and_resize_layer.cpp: In function '_vx_node* vxCropAndResizeLayer(vx_graph, vx_tensor, vx_tensor, vx_scalar, vx_scalar, vx_scalar, vx_scalar, vx_scalar, vx_scalar)':
/MIVisionX/amd_openvx_extensions/amd_nn/src/crop_and_resize_layer.cpp:277:34: error: 'VX_KERNEL_CROP_AND_RESIZE_LAYER_AMD' was not declared in this scope
         node = createNode(graph, VX_KERNEL_CROP_AND_RESIZE_LAYER_AMD, params, sizeof(params) / sizeof(params[0]));
                                  ^
amd_openvx_extensions/amd_nn/CMakeFiles/vx_nn.dir/build.make:662: recipe for target 'amd_openvx_extensions/amd_nn/CMakeFiles/vx_nn.dir/src/crop_and_resize_layer.cpp.o' failed
make[2]: *** [amd_openvx_extensions/amd_nn/CMakeFiles/vx_nn.dir/src/crop_and_resize_layer.cpp.o] Error 1
CMakeFiles/Makefile2:239: recipe for target 'amd_openvx_extensions/amd_nn/CMakeFiles/vx_nn.dir/all' failed
make[1]: *** [amd_openvx_extensions/amd_nn/CMakeFiles/vx_nn.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by kiritigowda** [comment]
@hansely you need to add this layer to be accessed by the conversion scripts and have a test case.

**Comment by LakshmiKumar23** [comment]
@hansely Can you add the cropLayer in kernels.h and kernels.cpp in this commit? If Kiriti merges both pull requests, either one of the layers would be missing in those files.

**Comment by kiritigowda** [comment]
@hansely as mentioned in PR #45, model compiler flow required for merge.

**Comment by kiritigowda** [comment]
@hansely this merge request has conflicts. Re-sync with master and open a new PR.

**Pull request closed without merging**
