### PR TITLE
H/ConstantOfShape_layer

### PR DESCRIPTION
**Pull request by hansely**
ConstantOfShape layer for onnx

### CODE REVIEW

**Comment by hansely** [comment]
Ready to be merged

**Comment by kiritigowda** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- model_compiler/python/nnir.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pullRequest?prid=5701980&bid=18662144)

**Comment by LakshmiKumar23** [comment]
@hansely do you have tests for this?

**Comment by hansely** [comment]
Preparing test cases

**Comment by kiritigowda** [comment]
@hansely let me know when this is ready to be merged

**Comment by kiritigowda** [comment]
@hansely can this be merged?

**Comment by hansely** [comment]
@kiritigowda Waiting for shape issue to be resolved first

**Comment by kiritigowda** [comment]
@hansely this branch has conflicts.

**Comment by hansely** [comment]
@kiritigowda  I'll close the PR until the shape issue is resolved. Once, we get a solution, I'll reopen the PR without any conflicts.

**Pull request closed without merging**
