### PR TITLE
rocAL - Changes in rali_unittests.cpp

### PR DESCRIPTION
**Pull request by Indumathi31**
Added command line option for each reader type.

### CODE REVIEW

**Comment by kiritigowda** [comment]
@Indumathi31 can you provide @paveltc with what tests to verify this PR? Thanks!

**Comment by Indumathi31** [comment]
@paveltc We have to test different readers supported in rali_unittest.cpp by specifying reader-type command line option

**Review by rrawther — APPROVED** [review]
@paveltc : please run rali-unittests before merge

**Review by paveltc — APPROVED** [review]
I have tested this and it is good to merge.

**Comment by kiritigowda** [comment]
@Indumathi31 - merge conflicts

**Comment by Indumathi31** [comment]
> @Indumathi31 - merge conflicts

Resolved merge conflicts @kiritigowda

**Pull request merged**
