### PR TITLE
OpenCV decoder support and TJ partial decoding with scale

### PR DESCRIPTION
**Pull request by rrawther**
Added OpenCV decoder as another decoder option for loading.
Added partial_decode_scale for TJ

### CODE REVIEW

**Comment by kiritigowda** [comment]
@paveltc can you run tests in this PR?

**Comment by rrawther** [comment]
@kiritigowda : Can we merge this? @paveltc tested this already

**Comment by kiritigowda** [comment]
@rrawther this PR is failing with the below error, can you see if this is related?

```
[ 99%] Building CXX object rali/rali/CMakeFiles/rali.dir/example.pb.cc.o
2664/MIVisionX/rali/rali/source/turbo_jpeg_decoder.cpp: In member function 'virtual Decoder::Status TJDecoder::decode(unsigned char*, size_t, unsigned char*, size_t, size_t, size_t, size_t, size_t&, size_t&, Decoder::ColorFormat, DecoderConfig, bool)':
2665/MIVisionX/rali/rali/source/turbo_jpeg_decoder.cpp:107:17: error: 'tjDecompress2_partial_scale' was not declared in this scope
2666             if( tjDecompress2_partial_scale(m_jpegDecompressor,
2667                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2668/MIVisionX/rali/rali/source/turbo_jpeg_decoder.cpp:107:17: note: suggested alternative: 'tjDecompress2_partial'
2669             if( tjDecompress2_partial_scale(m_jpegDecompressor,
2670                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2671                 tjDecompress2_partial
2672/MIVisionX/rali/rali/source/turbo_jpeg_decoder.cpp:189:17: error: 'tjDecompress2_partial_scale' was not declared in this scope
2673             if( tjDecompress2_partial_scale(m_jpegDecompressor,
2674                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2675/MIVisionX/rali/rali/source/turbo_jpeg_decoder.cpp:189:17: note: suggested alternative: 'tjDecompress2_partial'
2676             if( tjDecompress2_partial_scale(m_jpegDecompressor,
2677                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2678                 tjDecompress2_partial
2679rali/rali/CMakeFiles/rali.dir/build.make:2302: recipe for target 'rali/rali/CMakeFiles/rali.dir/source/turbo_jpeg_decoder.cpp.o' failed
2680make[2]: *** [rali/rali/CMakeFiles/rali.dir/source/turbo_jpeg_decoder.cpp.o] Error 1
2681make[2]: *** Waiting for unfinished jobs....
2682CMakeFiles/Makefile2:904: recipe for target 'rali/rali/CMakeFiles/rali.dir/all' failed
2683make[1]: *** [rali/rali/CMakeFiles/rali.dir/all] Error 2
2684Makefile:151: recipe for target 'all' failed
2685make: *** [all] Error 2
2686The command "docker exec mivisionx-5 cmake --build /_build --clean-first -- -j8" exited with 2.
2687
2688
2689Done. Your build exited with 1.
```

**Review by kiritigowda — APPROVED** [review]

**Comment by rrawther** [comment]
@kiritigowda : It needs turbojpeg decoder changes to support new functionality which is updated in the setup script. Please let me know if this is resolved with that

**Pull request merged**
