### PR TITLE
Setup Update - MIOpen Default - 2.5.0

### PR DESCRIPTION
**Pull request by kiritigowda**
* MIOpen Version upgrade - 2.5.0 to accommodate 3.6 ROCm changes.

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23  @paveltc we need to run the NN test with the new setup --reinstall

**Comment by LakshmiKumar23** [comment]
@kiritigowda @paveltc I see this when I run NN test.
```
fatal error: vx_amd_nn.h: No such file or directory
 #include <vx_amd_nn.h>
 ```

**Comment by kiritigowda** [comment]
> @kiritigowda @paveltc I see this when I run NN test.
> 
> ```
> fatal error: vx_amd_nn.h: No such file or directory
>  #include <vx_amd_nn.h>
> ```

@LakshmiKumar23 looks like the include file is not exported to /opt/rocm/mivisionx/include during install. Can you reinstall and try this.

**Comment by LakshmiKumar23** [comment]
> > @kiritigowda @paveltc I see this when I run NN test.
> > ```
> > fatal error: vx_amd_nn.h: No such file or directory
> >  #include <vx_amd_nn.h>
> > ```
> 
> @LakshmiKumar23 looks like the include file is not exported to /opt/rocm/mivisionx/include during install. Can you reinstall and try this.

@kiritigowda I was running it on a docker with old rocm and there were some install issues. Tried with latest docker. Anntest runs successfully.

**Pull request merged**
