### PR TITLE
AMD_MEDIA - PR#775 Update: this fixes the encoder issue encoding green frames.

### PR DESCRIPTION
**Pull request by rrawther**
Merged the API related changes from pr775, fixed bugs associated, fixed issue with encoder outputting green frames

### CODE REVIEW

**Comment by rrawther** [comment]
@kiritigowda : this has changes from pr775 as well. So that can be ignored.
@paveltc : I fixed the segmentation fault associated with PR775 and also fixed the encoder not producing correct output issue.

**Comment by acxz** [comment]
@rrawther thanks for taking this up. Sorry that I wasn't able to submit a complete PR.

**Comment by kiritigowda** [comment]
@paveltc can you test this and let me know if this is good to merge. Wanted to include this in the 5.0.2 release today. @rrawther

**Comment by paveltc** [comment]
@rrawther @kiritigowda Tested the PR and it works to encode H.264 files.

**Pull request merged**
