### PR TITLE
Nnef to nnir

### PR DESCRIPTION
**Pull request by hansely**
nnef update

### CODE REVIEW

**Comment by kiritigowda** [comment]
This pull request **introduces 4 alerts** and **fixes 1** when merging ec61ba2c8ae5cc2aebe471a9c2b6bb8d19d5f0c0 into 5c12598486e0735c91ea5d0f39def880fc958e78 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-2c6c13c83410a583cdcd05e0c7c2dd0bb574e8a4)

**new alerts:**

* 4 for Variable defined multiple times

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kiritigowda** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging a8cbbd21ab77ccde5d604a8ce652d7954e90d947 into 5c12598486e0735c91ea5d0f39def880fc958e78 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-0440d18ee9f9a6ae5e74de7d1184f35115a58edc)

**new alerts:**

* 2 for Variable defined multiple times

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kiritigowda** [comment]
@hansely is this ready to be merged?

**Comment by hansely** [comment]
Not yet. Will let you know.

**Comment by kiritigowda** [comment]
This pull request **introduces 2 alerts** and **fixes 2** when merging ff70f616cfb117ef168502b9e6e6b767a4b9bd7c into 666809f98aa5dbc5334e3edf7c3a16c23fe93a74 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-91a55f9a2c145380e3fb67f40feb2d6aa87ebc07)

**new alerts:**

* 2 for Variable defined multiple times

**fixed alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
