### PR TITLE
Lintian Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
* Fix Errors
  + extended-description-is-empty
  + missing-dependency-on-libc 
  + unstripped-binary-or-object

### CODE REVIEW

**Comment by kiritigowda** [comment]
@paveltc can you run a smoke test on this PR?

**Comment by paveltc** [comment]
@kiritigowda running them now.

**Review by paveltc — APPROVED** [review]

**Comment by paveltc** [comment]
@kiritigowda The smoke tests have passed.

**Review by paveltc — APPROVED** [review]
PR has been reviewed.

**Pull request merged**
