### PR TITLE
Mobilenet-SSD support

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
1. Added Detection Output Layer
2. Adds support for axis=2 in concat layer
3. Fixes permute layer
4. Fixes prior box layer
5. Adds support for axis =2 in softmax layer
6. Model compiler changes for the above

### CODE REVIEW

**Comment by kiritigowda** [comment]
This pull request **introduces 9 alerts** when merging f3a3ce975ceb29698b3be090c61c38375126db7f into a4eb13447034c0dabcde68b690b91d109ae754c2 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-b9ee1f3cc425592deed143f63bfd35d236abe376)

**new alerts:**

* 5 for Unused local variable
* 4 for Variable defined multiple times

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you look at the 9 alerts listed above

**Comment by kiritigowda** [comment]
This pull request **introduces 4 alerts** when merging 5cb9f89176b83cea0f297dc233ab743f8026898e into 35ce6e21662c61540f10436e8cf9f2555faec455 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-4d3e44fe0b69ed71be9cebf51871ecc06ceface9)

**new alerts:**

* 4 for Variable defined multiple times

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by LakshmiKumar23** [comment]
@kiritigowda Fixed the alerts

**Comment by paveltc** [comment]
Can also be merged.

**Pull request merged**
