### PR TITLE
CTS FIX - Seg Faults Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
* Fix 1 - SmokeTestBase.vxLoadKernels
```
[ RUN 0002 ] SmokeTestBase.vxLoadKernels ...
1236/home/travis/.travis/functions: line 109:  7192 Segmentation fault      (core dumped) LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance
1237The command "LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance" failed and exited with 139 during .
```

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you review

```
[ ======== ]
12947[ ALL DONE ] 5832 test(s) from 69 test case(s) ran
12948[ PASSED   ] 5832 test(s)
12949[ FAILED   ] 0 test(s)
12950[ DISABLED ] 8190 test(s)
12951
12952=================================
12953OpenVX Conformance report summary
12954=================================
12955
12956To be conformant to the OpenVX baseline, 875 required test(s) must pass. 875 tests passed, 0 tests failed. PASSED.
12957To be conformant to the Vision conformance profile, 4957 required test(s) must pass. 4957 tests passed, 0 tests failed. PASSED.
12920Note: The 8190 disabled tests are optional and are not considered for conformance.
12921
12922#REPORT: 20210408070110 ALL 15289 8190 5832 5832 5832 0 (version 1.3)
```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 & @hansely can you review this?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 & @hansely can you review this?

@kiritigowda Does the last commit change something major? I am running the test before your last commit

**Comment by kiritigowda** [comment]
> > @LakshmiKumar23 & @hansely can you review this?
> 
> @kiritigowda Does the last commit change something major? I am running the test before your last commit

@LakshmiKumar23 this is ready to be merged. This fixes the segfaults.

**Pull request merged**
