### PR TITLE
Crop Layer

### PR DESCRIPTION
**Pull request by hansely**
Crop layer added.

### CODE REVIEW

**Comment by kiritigowda** [comment]
@hansely This needs to be added in the documentation and conversion scripts.

**Comment by kiritigowda** [comment]
@hansely have you created the documentation of adding a layer to OpenVX NN extensions to be used by Model Compiler? I do not see the Crop layer added into the model compiler flow in this pull request, model compiler flow is required for the PR #45 to be merged.

**Comment by hansely** [comment]
I will add it now

**Comment by kiritigowda** [comment]
This pull request **introduces 2 alerts** when merging 78b7b7b5ad823e3515bca43a5580beb408672f19 into 0cff626d441f359705f5da4eac2218966680d9f5 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-08434b504d0b5899d5a796f9253eb69f7b39eab5)

**new alerts:**

* 2 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kiritigowda** [comment]
This pull request **introduces 2 alerts** when merging 2b285f70ff97d6263b146383e83ac6c53fab26ec into 0cff626d441f359705f5da4eac2218966680d9f5 - [view on LGTM.com](https://lgtm.com/projects/g/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/rev/pr-2550b30e29543fcc2eb14861316c516cf951dfea)

**new alerts:**

* 2 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kiritigowda** [comment]
@hansel is this branch ready to merge?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you build this branch before the merge?

**Comment by LakshmiKumar23** [comment]
@kiritigowda It builds successfully

**Pull request merged**
