### PR TITLE
WIP: ADAT - Improvements

### PR DESCRIPTION
**Pull request by bijayraj**
### Bug Fixes:
- [x] Alternate scoring - make optional with hierarchy
- [x] Alternate scoring - graphs missing
- [x] Hierarchy info missing from Images folder

### New Features:
- [x] Load command line arguments from json/ini file with --file option
- [x] Compare two files - new script to generate diff options
- [x] GUI for saving/editing configs, invoking visualizations

### Notes
- New python module "_csvdiff_" is required. Can be installed using `pip install csvdiff`.
- GUI uses pyqt4. 
- The diff is visible in "Image Result" table in generated HTML.

- The code is more modular with main functions moved to _"adat_classification.py"_ file.
- _"generate-visualization.py"_ is responsible for parsing command-line arguments and invoking html generate function from _"adat_classification.py"_
- _"adat_classification.py"_ can now be imported to external python scripts.

### CODE REVIEW

**Comment by kiritigowda** [comment]
@bijayraj missing 'import argparse`
```
 python toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py 
2020-11-09 17:53:36,540 [MainThread  ] [DEBUG]  AMD Data Analysis Toolkit - Classification
Traceback (most recent call last):
  File "toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py", line 70, in <module>
    main()
  File "toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py", line 37, in main
    parser = argparse.ArgumentParser()
```

**Comment by kiritigowda** [comment]
@bijayraj running `python toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py' script should open the GUI if no arguments are passed. Check out this app - https://github.com/kiritigowda/mivisionx-inference-analyzer for reference.

```
python toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py
2020-11-09 17:58:05,712 [MainThread  ] [DEBUG]  AMD Data Analysis Toolkit - Classification
Traceback (most recent call last):
  File "toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py", line 71, in <module>
    main()
  File "toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py", line 67, in main
    generateAnalysisOutput(argsDict)
  File "/Users/kiriti/work/adat/MIVisionX/toolkit/amd_data_analysis_toolkit/classification/adat_classification.py", line 1058, in generateAnalysisOutput
    validateConfig(argsDict)
  File "/Users/kiriti/work/adat/MIVisionX/toolkit/amd_data_analysis_toolkit/classification/adat_classification.py", line 1037, in validateConfig
    raise Exception(errorMessage)
Exception: Following required arguments were missing: 
--inference_results
--label
--output_dir
--output_name

```

**Comment by kiritigowda** [comment]
@bijayraj any updates on these?

**Comment by bijayraj** [comment]
> @bijayraj any updates on these?

@kiritigowda recent commits were made to fix the issues.

**Comment by kiritigowda** [comment]
@bijayraj - the following error when the new feature compare is used

```
python generate-visualization.py 
Traceback (most recent call last):
  File "/home/kiriti/adat/MIVisionX/toolkit/amd_data_analysis_toolkit/classification/adat_gui.py", line 161, in runGenerate
    ac.generateAnalysisOutput(self.configDict)
  File "/home/kiriti/adat/MIVisionX/toolkit/amd_data_analysis_toolkit/classification/adat_classification.py", line 1086, in generateAnalysisOutput
    diffPatch = getDifferencePatch(inputCSVFile, compareFile, ['FileName'])
  File "/home/kiriti/adat/MIVisionX/toolkit/amd_data_analysis_toolkit/classification/adat_classification.py", line 1146, in getDifferencePatch
    patch = csvdiff.diff_files(csv1, csv2, id_field)
  File "/home/kiriti/.local/lib/python2.7/site-packages/csvdiff/__init__.py", line 44, in diff_files
    ignore_columns=ignored_columns)
  File "/home/kiriti/.local/lib/python2.7/site-packages/csvdiff/patch.py", line 205, in create
    to_indexed = records.index(to_records, index_columns)
  File "/home/kiriti/.local/lib/python2.7/site-packages/csvdiff/records.py", line 58, in index
    raise InvalidKeyError('invalid column name {k} as key'.format(k=k))
csvdiff.records.InvalidKeyError: invalid column name 'FileName' as key

```

**Comment by bijayraj** [comment]
@kiritigowda New commit has fixed the problem. The problem was with incompatible compare file chosen. Extra file format checking has been added to avoid the error.

**Pull request closed without merging**
