### PR TITLE
VX - Security Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
* Security warnings fix
* Sprintf fix

### CODE REVIEW

**Comment by paveltc** [comment]
@kiritigowda I'm seeing the same errors as before with this PR.

**Comment by kiritigowda** [comment]
@paveltc this pr is ready to test, needs to run all the tests as core OpenVX functionality has been touched.

**Comment by kiritigowda** [comment]
@hansely can you test this branch and do a quick code review?

**Comment by hansely** [comment]
@kiritigowda Verified that the library is building without errors on Ubuntu22.04 rocm5.5. 
But there is one warning : 
```
lto-wapper: warning: using serial compilation of 8 LTRANS jobs
``` 
The code looks good as well.

**Comment by kiritigowda** [comment]
> @kiritigowda Verified that the library is building without errors on Ubuntu22.04 rocm5.5. But there is one warning :
> 
> ```
> lto-wapper: warning: using serial compilation of 8 LTRANS jobs
> ```
> 
> The code looks good as well.

Can you send me the warning log for U22.04 ?

**Comment by hansely** [comment]
> > @kiritigowda Verified that the library is building without errors on Ubuntu22.04 rocm5.5. But there is one warning :
> > ```
> > lto-wapper: warning: using serial compilation of 8 LTRANS jobs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The code looks good as well.
> 
> Can you send me the warning log for U22.04 ?

lto-wapper: warning: using serial compilation of 8 LTRANS jobs

This is all the warning message I got.

**Comment by paveltc** [comment]
@kiritigowda NN tests pass with this PR.

**Comment by kiritigowda** [comment]
Thanks @paveltc I will merge this into develop.

**Pull request merged**
