### PR TITLE
model compiler: py2to3 

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
Converted code base from python 2 to 3.
@paveltc This is the PR to run smoke tests on. Please use python3 and let me know if it complains of anything other than the module downloads. Will definitely need onnx, numpy, nnef for python3

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this compatible with IEEE PR?

**Review by kiritigowda — APPROVED** [review]
Approved, pending all test results

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 is this compatible with IEEE PR?

@kiritigowda I need to sync with master once after IEEE PR is merged. in case any merge conflicts arise

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you look at this change in the PR - [change](https://app.codacy.com/gh/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pullRequest?prid=6652327&bid=21393815)

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 can you look at this change in the PR - [change](https://app.codacy.com/gh/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pullRequest?prid=6652327&bid=21393815)

@kiritigowda Like I mentioned in the meeting, this was because of the future module. We will have to change everything to support only py3

**Comment by kiritigowda** [comment]
@LakshmiKumar23 any updates on this PR?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 any updates on this PR?

@kiritigowda @paveltc is running tests currently

**Comment by paveltc** [comment]
@kiritigowda and @LakshmiKumar23 This PR passed all of my tests. It can be merged.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 if you can look that these [2 issues](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/404/checks?check_run_id=1593260166) in the PR and try to solve them. If not relevant, mark as resolved.

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 if you can look that these [2 issues](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/404/checks?check_run_id=1593260166) in the PR and try to solve them. If not relevant, mark as resolved.

@kiritigowda Resolved issues. Unable to mark it though. It just says analysis successful

**Comment by kiritigowda** [comment]
@LakshmiKumar23 I will merge this. Can you also update the readme for the model compiler?

**Pull request merged**
