### PR TITLE
VxMapRemapPatch - Fix

### PR DESCRIPTION
**Pull request by kiritigowda**
Fix - Conditional jump on uninitialized value

### CODE REVIEW

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you verify the fix for VxMapRemapPatch?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 can you verify the fix for VxMapRemapPatch?

@kiritigowda I still see the random fails. I ran it thrice, and it failed twice. The random fail is still seen

**Comment by kiritigowda** [comment]
> > @LakshmiKumar23 can you verify the fix for VxMapRemapPatch?
> 
> @kiritigowda I still see the random fails. I ran it thrice, and it failed twice. The random fail is still seen

can you send me your run command?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 merging this to fix the Conditional jump on uninitialized value will look into remap patch again. Could not reproduce the failure after this fix.

**Pull request merged**
