### PR TITLE
Model Compiler - ONNX flow fix & Fuse Ops fix

### PR DESCRIPTION
**Pull request by hansely**
-This pr fixes onnx 'keyerror' issue
-This PR fixes the fuse ops issue where it tries to read the binary files when it is not there until the runtime

### CODE REVIEW

**Comment by paveltc** [comment]
This fixes the keyerror issue. I have been able to run alexnet 7, resnet50 2, squeezenet 7 and vgg16 7 all the way through anntest.
Alexnet 7 fails with fuseOn though.

**Comment by kiritigowda** [comment]
@hansely can you fix the codacy issues - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/1082/checks?check_run_id=13499916194

**Comment by hansely** [comment]
@kiritigowda fixed one of the two codacy issues. Fixing the other codacy issue will cause the keyerror issue. The PR is ready to be merged

**Comment by hansely** [comment]
All the models are now passing with fuse on.
```
RAN (ONNX): squeezenet, precision - FP32, batch size - 1
RAN (ONNX): squeezenet, precision - FP32, batch size - 2
RAN (ONNX): squeezenet, precision - FP32, batch size - 4
RAN (ONNX): squeezenet, precision - FP32, batch size - 8
RAN (ONNX): squeezenet, precision - FP32, batch size - 16
RAN (ONNX): squeezenet, precision - FP32, batch size - 32
RAN (ONNX): squeezenet, precision - FP32, batch size - 64
RAN (ONNX): squeezenet, precision - FP32, batch size - 128
RAN (ONNX): vgg19, precision - FP32, batch size - 1
RAN (ONNX): vgg19, precision - FP32, batch size - 2
RAN (ONNX): vgg19, precision - FP32, batch size - 4
RAN (ONNX): vgg19, precision - FP32, batch size - 8
RAN (ONNX): vgg19, precision - FP32, batch size - 16
RAN (ONNX): vgg19, precision - FP32, batch size - 32
RAN (ONNX): vgg19, precision - FP32, batch size - 64
RAN (ONNX): vgg19, precision - FP32, batch size - 128
RAN (ONNX): resnet50, precision - FP32, batch size - 1
RAN (ONNX): resnet50, precision - FP32, batch size - 2
RAN (ONNX): resnet50, precision - FP32, batch size - 4
RAN (ONNX): resnet50, precision - FP32, batch size - 8
RAN (ONNX): resnet50, precision - FP32, batch size - 16
RAN (ONNX): resnet50, precision - FP32, batch size - 32
RAN (ONNX): resnet50, precision - FP32, batch size - 64
RAN (ONNX): resnet50, precision - FP32, batch size - 128
RAN (ONNX): densenet, precision - FP32, batch size - 1
RAN (ONNX): densenet, precision - FP32, batch size - 2
RAN (ONNX): densenet, precision - FP32, batch size - 4
RAN (ONNX): densenet, precision - FP32, batch size - 8
RAN (ONNX): densenet, precision - FP32, batch size - 16
RAN (ONNX): densenet, precision - FP32, batch size - 32
RAN (ONNX): densenet, precision - FP32, batch size - 64
RAN (ONNX): densenet, precision - FP32, batch size - 128
RAN (ONNX): googlenet, precision - FP32, batch size - 1
RAN (ONNX): googlenet, precision - FP32, batch size - 2
RAN (ONNX): googlenet, precision - FP32, batch size - 4
RAN (ONNX): googlenet, precision - FP32, batch size - 8
RAN (ONNX): googlenet, precision - FP32, batch size - 16
RAN (ONNX): googlenet, precision - FP32, batch size - 32
RAN (ONNX): googlenet, precision - FP32, batch size - 64
RAN (ONNX): googlenet, precision - FP32, batch size - 128
```

Alexnet doesn't work since there is a group convolution failure issue with MIOpen.
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2067

**Comment by kiritigowda** [comment]
@paveltc can you test this?

**Review by kiritigowda — APPROVED** [review]

**Comment by paveltc** [comment]
Checked this yesterday. Should be good to merge.

**Comment by hansely** [comment]
@kiritigowda Can be merged now

**Pull request merged**
