### PR TITLE
added few optimizations for SSD

### PR DESCRIPTION
**Pull request by rrawther**

### CODE REVIEW

**Comment by rrawther** [comment]
@kiritigowda @LakshmiKumar23 : Can we merge this. Swetha verified that it passes SSD training

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you verify this PR?

**Comment by LakshmiKumar23** [comment]
@kiritigowda I spoke to Rajy, I finally have my machine, so I am running a baseline now. I will run this PR after that.

**Comment by LakshmiKumar23** [comment]
@kiritigowda can be merged. Merges at 50th epoch in 54 minutes

**Review by LakshmiKumar23 — APPROVED** [review]

**Pull request merged**
