### PR TITLE
Release updates - Develop Merge

### PR DESCRIPTION
**Pull request by kiritigowda**

### CODE REVIEW

**Comment by paveltc** [comment]
@kiritigowda I just ran the setup script with the HIP backend and then ran cmake.
I get the following message:
WARNING: MIGraphX or HIP Not Found -- vx_amd_migraphx module excluded

Do you know why this might be showing up considering that I did all of the prerequisite steps to have it included?

Thanks,
Pavel

**Comment by paveltc** [comment]
@kiritigowda I just ran the setup script with the HIP backend and then ran cmake.
I get the following message:
WARNING: MIGraphX or HIP Not Found -- vx_amd_migraphx module excluded

Do you know why this might be showing up considering that I did all of the prerequisite steps to have it included?

Thanks,
Pavel

**Comment by kiritigowda** [comment]
@paveltc -- The setup currently does not install MIGraphX Deps -- @asalmanp will setup get the MIGraphX apt install?

**Comment by asalmanp** [comment]
> @paveltc -- The setup currently does not install MIGraphX Deps -- @asalmanp will setup get the MIGraphX apt install?

@kiritigowda No, the setup won't install the MIGraphX.

**Comment by paveltc** [comment]
@kiritigowda I just tried MIVisionX-setup.py with the CPU backend. Then I ran cmake with the HIP backend for MIVisionX. It did not give an error saying that it won't build. It still says building with HIP.

**Comment by paveltc** [comment]
@kiritigowda I just tried MIVisionX-setup.py with the CPU backend. Then I ran cmake with the HIP backend for MIVisionX. It did not give an error saying that it won't build. It still says building with HIP.

**Comment by kiritigowda** [comment]
@paveltc this PR needs a comprehensive test pass to merge

**Pull request merged**
