### PR TITLE
OpenVX HIP backend - add linking to hip

### PR DESCRIPTION
**Pull request by asalmanp**

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@asalmanp Is this PR to make it HIP backend by default?

**Comment by asalmanp** [comment]
> @asalmanp Is this PR to make it HIP backend by default?

@LakshmiKumar23 No it is not. this is an enhancement for the OpenVX with the HIP backend. 

There will be a separate PR to make HIP the default GPU backend for the MIVisionX. I'll add you there once it is ready.

**Comment by LakshmiKumar23** [comment]
> > @asalmanp Is this PR to make it HIP backend by default?
> 
> @LakshmiKumar23 No it is not. this is an enhancement for the OpenVX with the HIP backend.
> 
> There will be a separate PR to make HIP the default GPU backend for the MIVisionX. I'll add you there once it is ready.

@asalmanp Any test I should run on this specifically? CI is passing

**Comment by asalmanp** [comment]
> > > @asalmanp Is this PR to make it HIP backend by default?
> > 
> > 
> > @LakshmiKumar23 No it is not. this is an enhancement for the OpenVX with the HIP backend.
> > There will be a separate PR to make HIP the default GPU backend for the MIVisionX. I'll add you there once it is ready.
> 
> @asalmanp Any test I should run on this specifically? CI is passing

The testing on CI should be fine, as it builds OpenVX with the HIP backend, tests conformance, and VisionTests.

**Review by LakshmiKumar23 — APPROVED** [review]

**Review by rrawther — APPROVED** [review]

**Pull request merged**
